name: Checkstyle

on:
  pull_request:
  schedule:
    - cron: '30 13 * * 2'

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run checkstyle verification
        run: ./gradlew checkstyleMain checkstyleTest